### ISSUE TITLE
Game

### ISSUE THREAD

**Issue by cerdelen** [cerdelen/42_transcendence#6]
1. Therefore, users should be able to play a live Pong game versus another player
directly on the website.

2. There must be a matchmaking system: the user can join a queue until they get
automatically matched with someone else.

3. It can be a canvas game, or it can be a game rendered in 3D, it can also be ugly,
but in any case, it must be faithful to the original Pong (1972).

4. You must offer some customization options (for example, power-ups or different
maps). However, the user should be able to select a default version of the game
without any extra features if they want to.

5. The game must be responsive!

6. The user should be able to watch a live play between other users without interfering
with it.

**Comment by jakubkaczmarski** [comment]
🦫
